version: '3'

networks:
  build-net:
    name: build-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/24"

services:
  rcncoin-box:
    build: .
    restart: unless-stopped
    networks:
      - build-net
    entrypoint: /entrypoint.sh
    #volumes:
    #  - ./cnccoin:/cnccoin
    ports:
      - "9666:9666"
      - "9665:9665"
